### ISSUE TITLE
New issue regarding dev/target and deletion - investigating

### ISSUE THREAD

**Issue by wtcox** [EnergyMashupLab/NIST-CTS-Agents#66]
I found when doing "git pull origin" to bring my local machine up to date with the changes to the development branch that I had multiple errors when doing a fresh build in Spring Tool Suite 4.4.1 produced 67 compilation errors, mostly ...project is missing required library... that would have been in dev/target/EML Spring Project/WEB-INF/lib/..

I'll annotate continuing build and run issues with the updated development branch as of March 16, 2020.

**Comment by wtcox** [comment]
Seems to work now.
